### PR TITLE
Add React Native MercadoPago

### PR DESCRIPTION
**Pull request by JonatanSalas**
# Why

This PR adds `react-native-mercadopago-px` to the `react-native-libraries.json`. `MercadoPago` is one of the biggest payment platforms from Latam.
 
# Checklist

If you added a new library:

- [X] Added it to **react-native-libraries.json**

If you added a feature or fixed a bug:

- [ ] Documented in this PR how to use the feature or replicate the bug.
- [ ] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Review by Simek — APPROVED** [review]
Thank you! 👍

**Comment by JonatanSalas** [comment]
@Simek you're welcome! Thank you for the faster review and merge!

**Comment by luism3861** [comment]
> # Why
> This PR adds `react-native-mercadopago-px` to the `react-native-libraries.json`. `MercadoPago` is one of the biggest payment platforms from Latam.
> 
> # Checklist
> If you added a new library:
> 
> * [x]  Added it to **react-native-libraries.json**
> 
> If you added a feature or fixed a bug:
> 
> * [ ]  Documented in this PR how to use the feature or replicate the bug.
> * [ ]  Documented in this PR how you fixed or created the feature.

amazing thanks for this PR!!

**Comment by luism3861** [comment]
@JonatanSalas  thanks for this PR amazing!!

**Pull request merged**
