### PR TITLE
feat: add thumbnails

### PR DESCRIPTION
**Pull request by gorhom**
# Why

closing #271

# Preview

On Desktop

ezgif-4-cba2f6e6d938

On Mobile

ezgif-4-aea6f8cd5cb2

# Test

you will need to add a library with thumbnails field 

```json
[
  ...,
  {
    "npmPkg": "@gorhom/animated-tabbar",
    "githubUrl": "https://github.com/gorhom/react-native-animated-tabbar",
    "ios": true,
    "android": true,
    "web": false,
    "expo": true,
    "examples": [
      "https://github.com/gorhom/react-native-animated-tabbar/tree/master/example"
    ],
    "images": [
      "https://raw.githubusercontent.com/gorhom/react-native-animated-tabbar/master/docs/previews/bubble.gif",
      "https://raw.githubusercontent.com/gorhom/react-native-animated-tabbar/master/docs/previews/flashy.gif"
    ]
  },
  ...,
]
```

# Checklist

If you added a feature or fixed a bug:

- [X] Documented in this PR how to use the feature or replicate the bug.

### CODE REVIEW

**Comment by brentvatne** [comment]
looks great @gorhom! we should be able to turn [this script](https://github.com/react-native-community/directory/blob/master/scripts/fetch-readme-images.js) back on and populate it with images from the readme if we want to do this in an automated way. what do you think?

**Comment by gorhom** [comment]
@brentvatne yeah it will be very helpful, but my concern was that not all images in readme are preview of the library.

However, we could let libraries' owner to set `thumbnails`, and as a fallback we run the `fetchReadmeImages` script ?

**Comment by gorhom** [comment]
> However, we could let libraries' owner to set thumbnails, and as a fallback we run the fetchReadmeImages script ?

@brentvatne 🙂

**Comment by brentvatne** [comment]
oops I thought I had responded @gorhom - sorry!

I think we can let people provide `thumbnails` and if they do we don't scrape them from README. Otherwise we fallback to README scraped images.

**Comment by gorhom** [comment]
> oops I thought I had responded @gorhom - sorry!
no worries,

>I think we can let people provide thumbnails and if they do we don't scrape them from README. Otherwise we fallback to README scraped images.
edit: maybe we can use a field called images instead? it would be more clear for folks who don't speak english natively

sounds good, im on it👍

**Comment by gorhom** [comment]
@brentvatne it's ready 👍

**Pull request merged**
