### PR TITLE
add dark mode and theme toggler

### PR DESCRIPTION
**Pull request by Simek**
# Why

This PR adds the dark mode theme support and theme toggler to the directory website. The changes and handling the appearance context are not organized and written in the most efficient/optimal way, but I want to reuse as much of the existing code and theme related architecture (appearance hook was not working properly in some places or components), but the current infra supports caching the selected theme in the device local storage. Overall there is no reason to not improve this in the future, it's just the initial version (same with design and colors,, they can be fully adjusted or changed).

Besides the dark mode and context related changes I had to introduce the following changes:

* add main CSS style file (`styles.css`) to fix Next.js container issues
* move `PreviewStyles` from Document to App file
* `CheckBox` component from the core has been replaced with custom and simple checkbox visualization
* remove the white background from PNG assets

# Preview
#### Index with filters and libraries list
Annotation 2020-07-19 133542

#### Libraries tags/labels and image preview
Untitled

### Filters in light mode after the changes
Annotation 2020-07-19 130712

# Checklist

If you added a feature or fixed a bug:

- [X] Documented in this PR how you fixed or created the feature.

### CODE REVIEW

**Comment by jonsamp** [comment]
I made a PR on your fork @Simek to improve some of the colors + add dark mode to /directory score: https://github.com/Simek/website-1/pull/1

**Comment by Simek** [comment]
Thank you for updating the Directory Score page, I have totally forgot about it. 😄

Also the colors improvements looks good to me!

**Comment by Simek** [comment]
> Also the colors improvements looks good to me!

@jonsamp But after browsering directory for a while I have a feeling that the borders in dark mode stands a bit too much (there is a bit too much lightness/contrast difference in my opinion) in comparison to the light mode.

**Comment by jonsamp** [comment]
> > Also the colors improvements looks good to me!
> 
> 
> 
> @jonsamp But after browsering directory for a while I have a feeling that the borders in dark mode stands a bit too much (there is a bit too much lightness/contrast difference in my opinion) in comparison to the light mode. 
> 
> 
> 
> There is a comparison after (top) and before (bottom) the change:
> 
> 87874675-ff7abf80-c9cb-11ea-81e5-3e57c6768e60

Feel free to use your color for the borders!

**Pull request merged**
